### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by dansimaa** [zqh0253/BerfScene#1]
Hi there, 
Thank you for sharing your project.
Upon exploring the repository, I've noticed that the file necessary to initiate training, `train.py`, seems to be missing. Could you please provide this file or advise on how to proceed with the training process?
Thanks in advance for your help with this.

Best regards,
Daniel

**Comment by zqh0253** [comment]
Hi Daniel,

Thanks for your interest in our project. I have added the `train.py` file.

Best regards,
Qihang

**Comment by dansimaa** [comment]
Perfect, Thank you!
